### PR TITLE
Fix support for no-op usage of this module

### LINKED ISSUE #2: Error with user_pool_arn on plan
https://github.com/rhythmictech/terraform-aws-elb-cognito-auth/blob/4f374e22dded1158764b54b98856faf2c966db7f/main.tf#L10

```
Error: Invalid index

  on .terraform/modules/cognitoauth/main.tf line 9, in locals:
   9:   user_pool_arn       = var.create_cognito_pool ? aws_cognito_user_pool.this[0].arn : var.user_pool_arn
    |----------------
    | aws_cognito_user_pool.this is empty tuple

The given key does not identify an element in this collection value.


Error: Invalid index

  on .terraform/modules/cognitoauth/main.tf line 10, in locals:
  10:   user_pool_client_id = var.create_cognito_pool ? aws_cognito_user_pool_client.this[0].id : var.user_pool_client_id
    |----------------
    | aws_cognito_user_pool_client.this is empty tuple

The given key does not identify an element in this collection value.


Error: Invalid index

  on .terraform/modules/cognitoauth/main.tf line 11, in locals:
  11:   user_pool_domain    = var.create_cognito_pool ? aws_cognito_user_pool_domain.this[0].domain : var.user_pool_domain
    |----------------
    | aws_cognito_user_pool_domain.this is empty tuple

The given key does not identify an element in this collection value.
```

See https://github.com/rhythmictech/gpe-aws-primary/pull/13

### PR DESCRIPTION
**Pull request by dgoodellrhy**
update outputs.tf to support scenario where aws_lib_listener_rule.this is not created

### CODE REVIEW

File: bin/install-ubuntu.sh [hunk 1]
```diff
@@ -3,8 +3,8 @@
 echo 'installing dependencies'
 sudo apt install python3-pip gawk &&\
 pip3 install pre-commit
-curl -L "$(curl -s https://api.github.com/repos/segmentio/terraform-docs/releases/latest | grep -o -E "https://.+?-linux-amd64")" > terraform-docs && chmod +x terraform-docs && sudo mv terraform-docs /usr/bin/
-curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" > tflint.zip && unzip tflint.zip && rm tflint.zip && sudo mv tflint /usr/bin/
+curl -sL "$(curl -s https://api.github.com/repos/segmentio/terraform-docs/releases/latest | grep -o -E "https://.+?-linux-amd64")" > terraform-docs && chmod +x terraform-docs && sudo mv terraform-docs /usr/bin/
```
Comment (cdaniluk) [inline bin/install-ubuntu.sh]:
```suggestion
curl -L "$(curl -sL https://api.github.com/repos/segmentio/terraform-docs/releases/latest | grep -o -E "https://.+?-linux-amd64")" > terraform-docs && chmod +x terraform-docs && sudo mv terraform-docs /usr/bin/
```

File: bin/install-ubuntu.sh [hunk 2]
```diff
@@ -3,8 +3,8 @@
...
+curl -sL "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" > tflint.zip && unzip tflint.zip && rm tflint.zip && sudo mv tflint /usr/bin/
```
Comment (cdaniluk) [inline bin/install-ubuntu.sh]:
```suggestion
curl -L "$(curl -sL https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" > tflint.zip && unzip tflint.zip && rm tflint.zip && sudo mv tflint /usr/bin/
```

**Review by cdaniluk — CHANGES_REQUESTED** [review]

**Comment by sblack4** [comment]
Can you get the ternaries in https://github.com/rhythmictech/terraform-aws-elb-cognito-auth/blob/4f374e22dded1158764b54b98856faf2c966db7f/main.tf#L11 for #2

**Review by cdaniluk — APPROVED** [review]
